# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‰ Thanks for opening your first issue here! Be sure to follow the issue template! We're excited to have you onboard. ğŸš€

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ‘ Thanks for opening this pull request! Please check out our contributing guidelines. Your contribution makes a difference! ğŸ’ª

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ¥³ Congrats on merging your first pull request! ğŸ‰ We here at Behaviorbot are proud of you! Keep up the great work! ğŸ™Œ ğŸ’¥
